
app-search-clients = 1
direct-reads = true
verbose = true
plugin-path = "/Users/jay/api/app-search-sync-plugins/mappings.so"
change-streams = true
resume = false
flush-interval = 10

[logs]
error = "/var/log/monstache/logs/error.log"
info = "/var/log/monstache/logs/info.log"

[[engineConfig]]
name = "targets-v1"
namespace = "tb_dev.targets_jay"
changeStreamNS = "tb_dev.targets_jay"
directReadNS = "tb_dev.targets_jay"
functionName = "TargetsMapping"
